// This enum was generated by Dialoguer
//	Do not modify this file, it will be overwritten by Dialoguer.
public enum DialoguerDialogues{
	TutorialMessage = 0,
	Amon_ChangeSubject = 1,
	Amon_Insult1 = 2,
	Amon_Insult2 = 3,
	Amon_Insult3 = 4,
	Amon_Insult4 = 5,
	Amon_Blackmail1 = 6,
	Amon_Blackmail2 = 7,
	Amon_Blackmail3 = 8,
	Amon_Blackmail4 = 9,
	Amon_Silence1 = 10,
	Amon_Silence2 = 11,
	Amon_Silence3 = 12,
	Amon_Silence4 = 13,
	Amon_Victory = 14,
	Amon_Defeat = 15,
	Amon_NoItem = 16,
	Amon_HolyWater = 17,
	Amon_Paperwork = 18,
	Amon_Photo1 = 19,
}
